"""Add system_prompt column to Prompt

Revision ID: c8ba4f103e90
Revises: a16e7cea927c
Create Date: 2025-05-13 20:07:59.609344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ba4f103e90'
down_revision = 'a16e7cea927c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('system_prompt', sa.Text(), nullable=True)
        )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')

    # ### end Alembic commands ###
